version: '3'



services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: 'My:S3cr3t'
    ports:
      - "30306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"

