services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "My:S3cr3t"
      MYSQL_DATABASE: "ecommerce"
    ports:
      - "30306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ec-net
    restart: always

  backend:
    container_name: backend
    image: fatmakamal21/ecommerce-backend:${TAG:-latest}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - ec-net
    restart: always

  frontend:
    container_name: frontend
    image: fatmakamal21/ecommerce-frontend:${TAG:-latest}
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - ec-net
    restart: always
# this is a comment to test webhook
networks:
  ec-net:
    driver: bridge
