pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials2')

        BACKEND_IMAGE = 'fatmakamal21/ecommerce-backend'
        FRONTEND_IMAGE = 'fatmakamal21/ecommerce-frontend'

        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Fatmaalzhraakamal/new.git'
            }
        }

        stage('Build Images') {
            steps {
                dir('ecommerce') {
                    sh """
                        docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
                        docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend
                    """
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh """
                    echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                """
            }
        }

        stage('Push Images') {
            steps {
                sh """
                    docker push $BACKEND_IMAGE:$IMAGE_TAG
                    docker push $FRONTEND_IMAGE:$IMAGE_TAG
                """
            }
        }

        stage('Deploy on compose for testing') {
            steps {
                dir('ecommerce') {
                    sh 'docker compose down -v'
                    sh "TAG=${IMAGE_TAG} docker compose up -d"
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'sleep 15'
                sh 'curl -f http://35.223.205.53:3001/'
            }
        }

  stage('test kubectl tool') {
    steps {
      sh 'kubectl get pods'
    }
}
stage('Deploy') {
    steps {
        dir('ecommerce') {
            sh """
            sed -i 's|IMAGE_TAG|${IMAGE_TAG}|g' k8s/backend/deployment.yaml
            sed -i 's|IMAGE_TAG|${IMAGE_TAG}|g' k8s/frontend/deployment.yaml

            kubectl apply -f k8s/

            kubectl rollout status deployment/backend
            kubectl rollout status deployment/frontend
            """
        }
    }
}
    }
}