pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials2')

        BACKEND_IMAGE = 'fatmakamal21/ecommerce-backend'
        FRONTEND_IMAGE = 'fatmakamal21/ecommerce-frontend'

        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    options {
        disableConcurrentBuilds()
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repo') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nourhann14/Automated_E-Commerce_Deployment_Platform.git'
            }
        }

        stage('Build Images') {
            steps {
                dir('ecommerce') {
                    sh """
                        docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
                        docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend
                    """
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh """
                    echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                """
            }
        }

        stage('Push Images') {
            steps {
                sh """
                    docker push $BACKEND_IMAGE:$IMAGE_TAG
                    docker push $FRONTEND_IMAGE:$IMAGE_TAG
                """
            }
        }

        // stage('Deploy on compose for testing') {
        //     steps {
        //         dir('ecommerce') {
        //             sh '''
        //                 docker compose down -v
        //                 TAG=${IMAGE_TAG} docker compose up -d
        //             '''
        //         }
        //     }
        // }



     

        stage('Deploy') {
            steps {
                dir('ecommerce') {
                    sh """
                        sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" k8s/backend/deployment.yaml
                        sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" k8s/frontend/deployment.yaml

                        echo "=== FRONTEND IMAGE AFTER SED ==="
                        grep image k8s/frontend/deployment.yaml

                        pwd
                        find . -name frontend/deployment.yaml

                       kubectl apply -f k8s/frontend/deployment.yaml
                       kubectl apply -f k8s/backend/deployment.yaml 

                       #    apply hpa for frontend and backend

                        kubectl apply -f k8s/frontend-hpa.yaml
                        kubectl apply -f k8s/backend-hpa.yaml
                        kubectl apply -f k8s/db-vpa.yaml

                        kubectl rollout status deployment/backend
                        kubectl rollout status deployment/frontend
                    """
                }
            }
        }


                stage('Smoke Test') {
            steps {
                  dir('ecommerce') {
                sh '''
                   


                    # Tier 1 + 2 + 3: frontend (nginx) is up and can reach backend (and DB via /api/health)
                    curl -fsS http://136.111.221.77:31400/api/health | grep -q '"ok":true'
                   
                
                '''
            }
            }
        }

    }
}
