---
- name: Common Setup for All Servers
  hosts: all_servers
  become: yes

  tasks:

    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - python3
          - python3-pip
        state: present
