[jenkins]
34.171.72.165 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mern-key

[k8s_master]
34.45.46.196 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mern-key

[k8s_workers]
136.114.56.192 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mern-key

[all_servers:children]
jenkins
k8s_master
k8s_workers
