[controller]
35.223.205.53 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mern-key

[kubernetes]
136.111.221.77 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mern-key

[all_servers:children]
controller
kubernetes