- import_playbook: playbooks/common.yml
- import_playbook: playbooks/setup_docker.yml
- import_playbook: playbooks/controller.yml    # ← was jenkins.yml
- import_playbook: playbooks/kubernetes.yml    # ← new
- import_playbook: playbooks/nginx.yml